project_name: cc-auth
version: 4
langs:
  - rust
targets:
  - arch: x86_64
    os: linux
    os_derivative: any
    os_version:
      type: no
  - arch: wasm32
    os: web
    os_derivative: any
    os_version:
      type: no
cache_files:
  - .git
  - Cargo.lock
  - target
artifacts: []
variables: []
place_artifacts_into_project_root: []
pipelines:
  - title: lint
    desc: Got from `LBRP Pipeline`.
    info: lbrp@0.1.0
    tags:
      - cargo
      - upx
      - reqwest
    default: true
    actions:
      - title: Lint x86_64
        desc: ""
        info: cargo-clippy@0.1.0
        tags:
          - cargo
          - clippy
        action:
          type: pre_build
          supported_langs:
            - rust
          commands:
            - bash_c: cargo clippy
              ignore_fails: false
              show_success_output: true
              show_bash_c: true
      - title: Lint wasm32
        desc: ""
        info: cargo-clippy@0.1.0
        tags:
          - cargo
          - clippy
        action:
          type: pre_build
          supported_langs:
            - rust
          commands:
            - bash_c: cargo clippy --target wasm32-unknown-unknown
              ignore_fails: false
              show_success_output: true
              show_bash_c: true
      - title: Format
        desc: Format `.rs` files
        info: cargo-fmt@0.1.0
        tags:
          - rust
          - cargo
          - fmt
        exec_in_project_dir: true
        action:
          type: pre_build
          supported_langs:
            - rust
          commands:
            - bash_c: cargo fmt -- --config tab_spaces=2,max_width=120 */**/*.rs
              ignore_fails: false
              show_success_output: false
              show_bash_c: true
              only_when_fresh: false
